### ISSUE TITLE
Error: Not enough bytes for cells data

### ISSUE THREAD

**Issue by ingria** [ton-community/disassembler#6]
For example, try disassembling this contract: `EQCkR1cGmnsE45N4K0otPl5EnxnRakmGqeJUNua5fkWhales`

**Comment by ex3ndr** [comment]
If you are trying to get DATA (not CODE) then you probably just use toncenter that performs hard truncate of BOC over certain limit, it is impossible to get data via toncenter for such big contract.

**Comment by ingria** [comment]
Yes, that was the problem. Thanks!
